In [2]:
import pandas as pd

In [5]:
processed = pd.read_csv("processed.csv")

In [18]:
processed["clean_risk"][0]

'risk factors factors that may affect future results the following risk factors and other information included in this should be carefully considered if any of the following risks occur the company s business financial condition operating results and cash flows could be materially adversely affected the risks and uncertainties described below are not the only ones the company faces additionally risks and uncertainties not presently known to the company or that it currently deems immaterial also may impair its business financial condition operating results and cash flows in the future risks relating to cambrex s business companies may discontinue or decrease their usage of cambrex s services the company has observed increasing pressure on the part of its customers to reduce costs including the use of its services and products as a result of macro economic trends and various market dynamics specifically affecting the pharmaceutical industry these customers could discontinue or decrease their usage of cambrex s services and products new technologies competition or a reduction in demand for cambrex s products could reduce sales the markets for the company s products are competitive and price sensitive the company s competitors may lower prices on products in the future and the company may in certain cases respond by lowering its prices conversely failure to anticipate and respond to price competition may hurt cambrex s market share some of the company s competitors also have significant financial operational and sales and marketing resources which may reduce the company s level of business companies may develop new technologies that would compete with the company s products or render its products obsolete several of cambrex s customers especially those that buy its generic apis have internal capabilities similar to cambrex s in addition demand for the company s products may weaken due to a reduction in r d budgets loss of distributors or other factors dollars in thousands except share data index the company s failure to obtain new contracts or renew existing contracts may adversely affect its business many of cambrex s contracts are short term in duration as a result the company must continually replace its contracts with new contracts to sustain its revenue in addition certain of the company s long term contracts may be cancelled or delayed by clients for any reason upon notice multiple cancellations or non renewals of significant contracts could materially impact the company s business failure to obtain products and raw materials from third party manufacturers could affect cambrex s ability to manufacture and deliver its products the company relies on third party manufacturers to supply many of its raw materials and intermediates in addition the company has a single source for supplies of some raw materials to its products manufacturing problems may occur with these and other outside sources if such problems occur the company cannot ensure that it will be able to manufacture its products profitably or on time disruptions to the company s or its customers manufacturing operations could adversely affect its results due to heavy reliance on manufacturing and related operations to produce and distribute the products the company sells the company could be adversely affected by disruptions to these operations or its customers operations any significant disruption to those operations for any reason such as labor unrest terrorism power interruptions fire or other events beyond the company s control could adversely affect its sales and customer relationships while insurance coverage may reimburse the company in part for profits lost from such disruptions any sustained reduction in the company s ability to provide these products would negatively impact its sales growth expectations cash flows and profitability failure to win early stage business opportunities can cause difficulty in winning future opportunities with that potential customer certain products the company sells are incorporated into its customers drug manufacturing processes in some cases once a customer chooses a particular product for use in a drug manufacturing process it is unlikely that the customer will later switch to a competing alternative in many cases the regulatory approvals related to a drug product will specify the products qualified for use in its making obtaining the regulatory approvals needed for a change in the manufacturing process is time consuming expensive and uncertain accordingly if a customer does not select the company s products or services early in its manufacturing design phase for any number of reasons the company may lose the opportunity to participate in the customer s manufacturing of such product because the company faces competition in this market from other companies it is possible that its competitors could win significant early business with customers making it difficult for the company to recover late stage opportunities with higher volumes litigation may harm the company or otherwise negatively impact its management and financial resources complex or extended litigation could cause the company to incur large expenditures and distract its management for example lawsuits by employees stockholders counterparties to acquisition and divestiture contracts collaborators distributors customers or end users of the company s products or services could be very costly and substantially disrupt its business disputes from time to time with such companies or individuals are not uncommon and the company cannot be assured that it will always be able to resolve such disputes out of court or on terms favorable to the company refer to note for a discussion of the company s environmental and legal matters dollars in thousands except share data index incidents related to hazardous materials could adversely affect the company portions of the company s operations require the controlled use of hazardous materials although the company is diligent in designing and implementing safety procedures to comply with the standards prescribed by federal state local and foreign regulations including the european commission s registration evaluation and authorization of chemicals reach regulation the risk of accidental contamination of property or injury to individuals from these materials cannot be completely eliminated in the event of such an incident the company could be liable for any damages which could adversely affect its business additionally any incident could shut down the company s research and manufacturing facilities and operations the company generates waste that must be transported to approved storage treatment and disposal facilities the transportation and disposal of such waste are required to meet applicable state and federal statutes and regulations the storage treatment and disposal of such waste potentially exposes the company to environmental liability if in the future such transportation and disposal are deemed to have violated such statutes or regulations or if the storage treatment and disposal facilities are inadequate and are proved to have damaged the environment the company is also party to several environmental remediation investigations and cleanups and along with other companies has been named a potentially responsible party prp for certain waste disposal sites refer to note for a discussion of the company s environmental and legal matters potential product liability claims errors and omissions claims in connection with services the company performs and potential liability under indemnification agreements between the company and its officers and directors could adversely affect the company the company manufactures products intended for use by the public these activities could expose the company to risk of liability for personal injury or death to persons using such products the company seeks to reduce its potential liability through measures such as contractual indemnification provisions with customers the scope of which may vary by customer and the performances of which are not secured and insurance maintained by customers the company could be materially and adversely affected if it were required to pay damages or incur defense costs in connection with a claim that is outside the scope of the indemnification agreements if the indemnity although applicable is not performed in accordance with its terms or if the company s liability exceeds the amount of applicable insurance or indemnity in addition the company could be held liable for errors and omissions in connection with the services it performs the company currently maintains product liability and errors and omissions insurance with respect to these risks there can be no assurance however that the company s insurance coverage will be adequate or that insurance coverage will continue to be available on terms acceptable to the company the company also indemnifies its officers and directors for certain events or occurrences while the officer or director is or was serving at the company s request in such capacity the maximum potential amount of future payments the company could be required to make under these indemnification agreements is unlimited however the company has a director and officer insurance policy that covers a portion of any potential exposure the company could be materially and adversely affected if it were required to pay damages or incur legal costs in connection with a claim above its insurance limits while the company has what it believes to be adequate insurance coverage any claims beyond its insurance coverage may result in substantial costs and a reduction in its available capital resources the company maintains property insurance policies covering physical damage to its equipment facilities buildings and inventory employer s liability insurance generally covering death or work injury of employees product liability insurance covering product liability claims arising from the use consumption or operation of its products general liability insurance covering certain incidents to third parties that occur on or in the premises of the company business interruption insurance and directors and officers liability insurance among others the company does not maintain key man life insurance on any of its senior management or key personnel the company s insurance coverage however may not be sufficient to cover any claim for product liability damage to its fixed assets or injury to its e mployees dollars in thousands except share data index loss of key personnel could hurt the company the company depends on its ability to attract and retain qualified scientific and technical employees as well as a number of key executives there can be no assurance the company will be able to retain key personnel or to attract and retain additional qualified employees the company s inability to attract and retain key personnel would have a material adverse effect on the company s business the company has made significant capital investments to its facilities to meet its potential future needs and as a result the company depends on the success of attracting new and retaining existing customers projects and their continued business the company has recently made substantial investments in all of its manufacturing facilities with the completion of these new facilities the company s fixed costs have increased if the company is not able to utilize the facilities to capacity its margins could be adversely affected global growth is subject to a number of economic risks the tightening of credit in financial markets in recent years adversely affects the ability of the company s customers to obtain financing for significant purchases and operations and could result in a decrease in or cancellation of orders for its products and services as well as impact the ability of the company s customers to make payments the company believes that cash flows from operations along with funds available from a revolving line of credit will be adequate to meet the operational and debt servicing needs of the company but no assurances can be given that this will continue to be the case there is a risk that the funds available to be drawn under the company s revolving line of credit may not be available in the event of the failure of one or more participant banks strengthening of the rate of exchange for the u s dollar against certain major currencies such as the euro swedish krona and other currencies may also adversely affects the company s results if the company acquires other companies its business may be harmed by difficulties in integration and employee retention unidentified liabilities of the acquired companies or obligations incurred in connection with acquisition financings all acquisitions involve known and unknown risks that could adversely affect the company s future revenues and operating results for example the company may fail to successfully integrate its acquisitions in accordance with its business strategy the initial rationale for the acquisition may not remain viable due to a variety of factors including unforeseen regulatory changes and market dynamics after the acquisition and this may result in a significant delay and or reduction in the profitability of the acquisition integration of acquisitions may divert management s attention away from the company s primary product offerings resulting in the loss of key customers and or personnel and may expose the company to unanticipated liabilities the company may not be able to retain the skilled employees and experienced management that may be necessary to operate the businesses it acquires if the company cannot retain such personnel it may not be able to locate or hire new skilled employees and experienced management to replace them cambrex may purchase a company that has contingent liabilities that include among others known or unknown patent or product liability claims the company s acquisition strategy may require it to obtain additional debt or equity financing resulting in additional leverage or increased debt obligations as compared to equity and dilution of ownership cambrex may purchase companies located in jurisdictions where it does not have operations and as a result it may not be able to anticipate local regulations and the impact such regulations have on its business dollars in thousands except share data index in addition if the company makes one or more significant acquisitions in which the consideration includes equity shares or other securities equity interests in cambrex held by holders of the equity shares may be significantly diluted and may result in a dilution of earnings per equity share if the company makes one or more significant acquisitions in which the consideration includes cash it may be required to use a substantial portion of its available cash or incur a significant amount of debt or otherwise arrange additional funds to complete the acquisition which may result in reduced liquidity a decrease in its net income and a consequential reduction in its earnings per equity share there are risks associated with the company s recent acquisition of a equity stake in zenara including but not limited to cambrex s ability to achieve its goals established for that business and fund its obligation to purchase the remaining in in november the company purchased of the equity in zenara for approximately and is required to purchase the remaining in based upon a formula derived from zenara s future ebitda the company may at its option purchase the remaining equity in cash or a combination of cash and up to of the consideration in cambrex stock to the extent zenara has significant ebitda over the next five years substantial consideration will be required to purchase the remaining a large cash payment could require borrowing under the company s credit facility and since the company s credit facility will need to be refinanced prior to its expiration in april there is no guarantee that the company s future credit arrangements will facilitate the future purchase of the remaining in additionally the uncertainty regarding the amount of consideration required for the buyout of the may impact the company s future borrowing ability result in higher interest expense or possibly result in difficulty securing any credit arrangements in the future additionally issuance of any stock to satisfy a portion of this obli gation could have a dilutive effect on holders of cambrex common stock in the event that cambrex is unable to compensate the equity holder for its shares in the shareholder has certain rights including the right to force a sale of zenara to a third party to secure their payment zenara is currently not profitable and there is no guarantee that it will be in the future should zenara not meet its goals or continue to generate losses it could negatively impact the company s consolidated results cash flows and stock price the company has a significant amount of debt the company has a revolving credit facility of which was outstanding at this facility expires in april if the company is unable to generate sufficient cash flow or otherwise obtain funds necessary to make required payments on the credit facility it will be in default this current debt arrangement requires the company to comply with specified financial ratios the company s ability to comply with these ratios may be affected by events beyond its control even if the company is able to meet its debt service obligations the amount of debt it has could adversely affect the company by limiting its ability to obtain any necessary financing in the future for working capital capital expenditures debt service requirements or other purposes it also places the company at a disadvantage relative to its competitors who have lower levels of debt while making it more vulnerable to a downturn in its business or the economy in general it also requires the company to use a substantial portion of its cash to pay principal and interest on its debt instead of investing those funds in the business the company s liquidity business financial condition results of operations and cash flows could be materially and adversely affected if the financial institutions which hold its funds fail the company has significant funds held in bank deposits money market funds and other accounts at certain financial institutions a significant portion of the funds held in these accounts exceed insurable limits if any of the financial institutions where the company has deposited funds were to fail the company may lose some or all of its deposited funds that exceed the insurance coverage limit such a loss would have a material and adverse effect on the company s liquidity business financial condition results of operations and cash flows dollars in thousands except share data index a payment failure by any large customer or multiple smaller customers could adversely affect the company s cash flows and profitability historically the company has not experienced any significant bad debt or collection problems but such problems may arise in the future the failure of any of the company s customers to make timely payments could require the company to write off accounts receivable or increase provisions made against its accounts receivable either of which could adversely affect the company s cash flows and profitability the company has significant inventories on hand the company maintains significant inventories and has an allowance for slow moving and obsolete inventory any significant unanticipated changes in future product demand or market conditions including the current uncertainty in the global market could also have an impact on the value of inventory and adversely impact the company s results of operations international unrest or foreign currency fluctuations could adversely affect the company s results the company s internation

In [21]:
processed[processed["clean_business"].str.len()> 1000]

,company_name,text,clean_risk,clean_mda,clean_business,clean_financials,risk_score,label
0,CAMBREX CORP,risk factors factors that may affect future re...,risk factors factors that may affect future re...,management s discussion and analysis of financ...,business general cambrex corporation the compa...,NaN,0.825133,high_risk
1,ADMINISTAFF INC \DE\,factors that may affect future results and the...,factors that may affect future results and the...,you should read the following discussion in co...,general administaff is a human resource hr ser...,the information required by this is contained ...,0.839448,high_risk
2,NSTAR ELECTRIC CO,nstar electric s future performance is subject...,nstar electric s future performance is subject...,overview nstar electric company is a regulated...,a general development of business nstar electr...,nstar electric company consolidated statements...,0.550473,high_risk
5,"Eco Energy Pumps, Inc.",risk factors risk related to our business beca...,risk factors risk related to our business beca...,management s discussion and analysis of financ...,business organizational history eco energy pum...,financial statements and supplementary financi...,-1.650111,low_risk
6,COPYTELE INC,risk factors our business involves a high degr...,risk factors our business involves a high degr...,management s discussion and analysis of financ...,business forward looking statements informatio...,financial statements and supplementary data se...,-2.095272,low_risk
...,...,...,...,...,...,...,...,...
2395,AMERISERV FINANCIAL INC /PA/,investors should carefully consider the risks ...,investors should carefully consider the risks ...,the following discussion and analysis of finan...,general ameriserv financial inc the company is...,ameriserv financial inc consolidated balance s...,-0.158822,medium_risk
2396,AMPAL-AMERICAN ISRAEL CORP,risk factors an investment in our securities i...,risk factors an investment in our securities i...,management s discussion and analysis of financ...,business as used in this report on form k the ...,financial statements and supplementary data se...,0.110340,medium_risk
2397,GTSI CORP,there are many factors that affect our busines...,there are many factors that affect our busines...,the following discussion and analysis is provi...,overview founded in gtsi corp is a delaware co...,report of independent registered public accoun...,-0.117922,medium_risk
2398,AMERICAN HOMEPATIENT INC,this section summarizes certain risks among ot...,this section summarizes certain risks among ot...,general the company provides home health care ...,introduction american homepatient inc and its ...,financial statements are contained on pages th...,-0.237989,medium_risk
2399,PALOMAR MEDICAL TECHNOLOGIES INC,this report contains forward looking statement...,this report contains forward looking statement...,forward looking statements this contains forwa...,palomar is a leading researcher and developer ...,palomar medical technologies inc and subsidiar...,0.180389,medium_risk

In [15]:
processed[processed["clean_financials"].str.len() > 200]

,company_name,text,clean_risk,clean_mda,clean_business,clean_financials,risk_score,label
2,NSTAR ELECTRIC CO,nstar electric s future performance is subject...,nstar electric s future performance is subject...,overview nstar electric company is a regulated...,a general development of business nstar electr...,nstar electric company consolidated statements...,0.550473,high_risk
3,"1st United Bancorp, Inc.",risk factors an investment in our common stock...,risk factors an investment in our common stock...,management s discussion and analysis of financ...,NaN,financial statements and supplementary data re...,1.145990,high_risk
4,Univest Tech Inc.,we have no successful history of operations ha...,we have no successful history of operations ha...,this management s discussion and analysis or p...,NaN,univest tech inc financial statements with rep...,-1.585833,low_risk
7,YUM BRANDS INC,risk factors you should carefully review the r...,risk factors you should carefully review the r...,management s discussion and analysis of financ...,business yum brands inc referred to herein as ...,financial statements and supplementary data in...,-0.118211,medium_risk
8,IMPLANT SCIENCES CORP,risk factors an investment in our common stock...,risk factors an investment in our common stock...,management s discussion and analysis of financ...,business cautionary note regarding forward loo...,financial statements and supplementary data th...,0.310602,high_risk
...,...,...,...,...,...,...,...,...
2393,"Hangman Productions, Inc.",the company s business operations are highly s...,the company s business operations are highly s...,safe harbor for forward looking statements whe...,historical developments hangman productions in...,part f s hangman productions inc a development...,-0.473693,low_risk
2394,DIXIE GROUP INC,in addition to the other information provided ...,in addition to the other information provided ...,the following discussion and analysis should b...,general our business consists principally of m...,list of financial statements and financial sta...,0.070753,medium_risk
2395,AMERISERV FINANCIAL INC /PA/,investors should carefully consider the risks ...,investors should carefully consider the risks ...,the following discussion and analysis of finan...,general ameriserv financial inc the company is...,ameriserv financial inc consolidated balance s...,-0.158822,medium_risk
2397,GTSI CORP,there are many factors that affect our busines...,there are many factors that affect our busines...,the following discussion and analysis is provi...,overview founded in gtsi corp is a delaware co...,report of independent registered public accoun...,-0.117922,medium_risk
2399,PALOMAR MEDICAL TECHNOLOGIES INC,this report contains forward looking statement...,this report contains forward looking statement...,forward looking statements this contains forwa...,palomar is a leading researcher and developer ...,palomar medical technologies inc and subsidiar...,0.180389,medium_risk